//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;

    public partial class Account
    {
        public int Id { get; set; }
        [DisplayName("Registration Number")]
        public string RegistrationNumber { get; set; }
        [DisplayName("Due Fees")]
        public decimal DueFee { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
