//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;


    public partial class Branch
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Initial { get; set; }
        [DisplayName("Course ID")]
        public int CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
