//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;

    public partial class Hostel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hostel()
        {
            this.Students = new HashSet<Student>();
        }
        [DisplayName("Bolck Number")]
        [Required(ErrorMessage = "This Field is Required")]
        public int BlockNumber { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("Room Type")]
        public string RoomType { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("Attached Bathroom")]
        public string AttachedBathroom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
