//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Accounts = new HashSet<Account>();
        }
        
        [Required(ErrorMessage = "This Field is Required")]
        public string Name { get; set; }
        [DisplayName("Registration Number")]
        [Required(ErrorMessage = "This Field is Required")]
        public string RegistrationNumber { get; set; }
        [DisplayName("Mother Name")]
        [Required(ErrorMessage = "This Field is Required")]
        public string MotherName { get; set; }
        [DisplayName("Father Name")]
        [Required(ErrorMessage = "This Field is Required")]
        public string FatherName { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Sex { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public System.DateTime DOB { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public string phone { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Course { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Branch { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public int Semester { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public int Hostel { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Hostel Hostel1 { get; set; }
    }
}
