//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMSDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;

    public partial class Subject
    {
        [DisplayName("Subject Code")]
        [Required(ErrorMessage = "This Field is Required")]
        public string SubjectCode { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("Course ID")]
        public int CourseID { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Faculty { get; set; }
        

        public virtual Course Course { get; set; }
        public virtual Faculty Faculty1 { get; set; }
    }
}
